
# TO RUN: docker compose up
# FOR DEBUG (with shell): docker compose run --rm videowall /bin/bash


services:
  videowall:
    build:
        context: .
        dockerfile: Dockerfile  # or path to your specific Dockerfile
    image: vwvisioncontroller
    container_name: videowall
    runtime: nvidia
    command: python3 -m VisionController
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - DISPLAY=:0
      - NVIDIA_DRIVER_CAPABILITIES=all
      - NVIDIA_VISIBLE_DEVICES=all
      - QT_X11_NO_MITSHM=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /etc/X11:/etc/X11
      - ~/.Xauthority:/root/.Xauthority
      - ./tmp:/app/tmp
      - ./VisionController:/app/VisionController
    network_mode: host
    working_dir: /app
    tty: true
    stdin_open: true
    privileged: false
    restart: always

  videowallinfer:
    image: vwvisioncontrollerinfer:7.0
    runtime: nvidia
    command: /bin/bash
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - DISPLAY=${DISPLAY}
      - NVIDIA_DRIVER_CAPABILITIES=all
      - NVIDIA_VISIBLE_DEVICES=all
      - QT_X11_NO_MITSHM=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /etc/X11:/etc/X11
      - ~/.Xauthority:/root/.Xauthority
      - ./tmp:/app/tmp
      - ./VisionController:/app/VisionController
    network_mode: host
    working_dir: /app
    tty: true
    stdin_open: true
    privileged: false
    restart: always

  videowall-dev:
    image: vwvisioncontrollerinfer:7.0
    container_name: vw-dev
    runtime: nvidia
    command: /bin/bash
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - DISPLAY=${DISPLAY}
      - NVIDIA_DRIVER_CAPABILITIES=all
      - NVIDIA_VISIBLE_DEVICES=all
      - QT_X11_NO_MITSHM=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /etc/X11:/etc/X11
      - ~/.Xauthority:/root/.Xauthority
      - ./tmp:/app/tmp
      - ./VisionController:/app/VisionController
    network_mode: host
    working_dir: /app
    tty: true
    stdin_open: true
    privileged: false
    restart: always
    
  videowallinfer71:
    image: vwvisioncontrollerinfer:7.1
    runtime: nvidia
    command: /bin/bash
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - DISPLAY=${DISPLAY}
      - NVIDIA_DRIVER_CAPABILITIES=all
      - NVIDIA_VISIBLE_DEVICES=all
      - QT_X11_NO_MITSHM=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /etc/X11:/etc/X11
      - ~/.Xauthority:/root/.Xauthority
      - ./tmp:/app/tmp
    network_mode: host
    working_dir: /app
    tty: true
    stdin_open: true
    privileged: false
    restart: always
