general:
  visca_port: 1000
  enable_aravis: false
  text_default_font: "Noto Serif Bold"
  symnbol_default_font: "MaterialSymbolsOutlined-Medium"

camera_providers:
  Axis:
    enabled: true
    type: Axis
    controller_file: "/app/VisionController/libs/cameras/vapix_control.py"
    controller_class: "VapixControl"
    source_bin_file: "/app/VisionController/libs/cameras/nvuri_source_bin.py"
    source_bin_func: "create_source_bin"
    kwargs: {}

  Test:
    enabled: true
    type: Test
    controller_file: ""
    controller_class: ""
    source_bin_file: "/app/VisionController/libs/cameras/placeholder_source_bin.py"
    source_bin_func: "create_source_bin"
    kwargs: {}

  Placeholder:
    enabled: true
    type: Placeholder
    controller_file: ""
    controller_class: ""
    source_bin_file: "/app/VisionController/libs/cameras/placeholder_source_bin.py"
    source_bin_func: "create_source_bin"
    kwargs: {}

  Z3:
    enabled: true
    type: Z3
    controller_file: 
    controller_class:
    source_bin_file: "/app/VisionController/libs/cameras/nvuri_source_bin.py"
    source_bin_func: "create_source_bin"
    kwargs: {}


mqtt:
  # broker: '192.168.181.204'
  # broker: '192.168.180.13'
  # broker: '10.1.3.180'
  # broker: '10.1.3.50'
  broker: 10.5.11.65
  port: 1883


  # ---- MQTT topics ---- #
  # Following are topics. Some topics have an optional qos parameter. Default is 0.

  # VWController/VisionController0/Tile01/Source = "Camera01"
  # VWController/VisionController0/Tile01/Brightness = 0.5
  # VWController/VisionController0/Tile01/OSD = {"OSDPort":{".Alignment.Value":"Center",".BGColor.Value":"0.0,0.0,0.0,0.6",".FontColor.Value":"1.0,1.0,1.0,1.0",".FontName.Value":"",".FontSize.Value":"18",".PosX.Value":"0",".PosY.Value":"0",".Text.Value":"",".TextIndex":"0",".TextProp":"",".Timeout.Value":"0"},"OSDPort1":{".Alignment.Value":"left",".BGColor.Value":"0.0,0.0,0.0,0.6",".FontColor.Value":"1.0,1.0,1.0,1.0",".FontName.Value":"",".Font…



  # Camera configuration
  cameras:
    names:
      - 'Camera01'
      - 'Camera02'
      - 'Camera03'
      - 'Camera04'
      - 'Camera05'
      - 'Camera06'
      - 'Camera07'
      - 'Camera08'
      - 'Camera09'
    subtopics:
      - 'DisplayName'
      - 'IP'
      - 'Width'
      - 'Height'
      - 'URI'
      - 'Framerate'
      - 'Format'
      - 'Type'

  vision_controllers:
    names:
      - 'VisionController0'
    subtopics:
      - 'IP'
      - 'Width'
      - 'Height'
      - 'TilerRows'
      - 'TilerColumns'
      - 'Fullscreen'
      - 'Shutdown': 1
      - 'StartPipeline': 1
    tiles:
      names:
        - 'Tile01'
        - 'Tile02'
        - 'Tile03'
        - 'Tile04'
        - 'Fullscreen'
      subtopics:
        - 'Source'
        - 'Enable'
        - 'Brightness'
        - 'ZoomSpeed'
        - 'PanSpeed'
        - 'TiltSpeed'
        - 'OSD'

pipeline:
  tiler_rows: 2
  tiler_columns: 2  
  width: 3840
  height: 2160
  sink_element: 'nv3dsink'
  streammux_config: '/app/VideoWallOrin/VisionController/config/config_nvstreammux.txt'
  max_num_sources: 4
  batched_push_timeout: 20000
  batch_size: 4
  sync_inputs: 0
  enable_pipeline: false
