general:
  visca_port: 1000

mqtt:
  broker: '192.168.181.204'
  # broker: '192.168.180.13'
  port: 1883

  # Following are topics. Some topics have an optional qos parameter. Default is 0.

  # Cameras are defined in the form 'Cameras/Camera0/'
  cameras:  
    - 'Camera1'
    - 'Camera2'
    - 'Camera3'
    - 'Camera4'
    - 'Camera5'
    - 'Camera6'
  camera_subtopics: 
    - 'IP'
    - 'Type'
    - 'Width'
    - 'Height'
    - 'Format'
    - 'Framerate'
    - 'Zoom'
    - 'Exposure'
    - 'ExposureAuto'
    - 'Gain'  
    - 'GainAuto'
    - 'Name'

  # VisionControllers are defined in the form 'VisionControllers/VisionController0/'
  vision_controllers: 
    - 'VisionController0'
  vision_controller_subtopics:
    - 'IP'
    - 'Width'
    - 'Height'
    - 'TilerRows'
    - 'TilerColumns'
    - 'Fullscreen'
    - 'Shutdown': 1
    - 'StartPipeline': 1

  # There are four tiles in the form 'VisionControllers/VisionController0/TileXX/'

  tile_subtopics:
    - 'Source'
    - 'Enable'
    - 'Exposure'
    - 'ExposureAuto'
    - 'Gain'
    - 'Zoom'

pipeline:
  tiler_rows: 2
  tiler_columns: 2  
  width: 3840
  height: 2160
  sink_element: 'nv3dsink'
  streammux_config: '/home/seaonics/Dev/VideoWallOrin/VisionController/config/streammux_config.txt'
  max_num_sources: 4
  batched_push_timeout: 20000
  batch_size: 4
  sync_inputs: 0
  enable_pipeline: false
