general:
  visca_port: 1000

mqtt:
  broker: '192.168.181.204'
  # broker: '192.168.180.13'
  port: 1883

  # Following are topics. Some topics have an optional qos parameter. Default is 0.

  # Cameras are defined in the form 'Cameras/Camera0/'
  cameras:  
    - 'Cameras/Camera1/'
    - 'Cameras/Camera2/'
    - 'Cameras/Camera3/'
    - 'Cameras/Camera4/'
    - 'Cameras/Camera5/'
    - 'Cameras/Camera6/'
  camera_subtopics: 
    - 'IP'
    - 'Type'
    - 'Width'
    - 'Height'
    - 'Format'
    - 'Framerate'
    - 'Zoom'
    - 'Exposure'
    - 'ExposureAuto'
    - 'Gain'
    - 'GainAuto'

  # VisionControllers are defined in the form 'VisionControllers/VisionController0/'
  vision_controllers: 
    - 'VisionControllers/VisionController0/'
  vision_controller_subtopics:
    - 'IP'
    - 'Width'
    - 'Height'
    - 'TilerRows'
    - 'TilerColumns'
    - 'Fullscreen'
    - 'Shutdown': 1
    - 'StartPipeline': 1
    # - 'Tile00/Source'
    # - 'Tile00/Enable'
    - 'Tile01/Source'
    - 'Tile01/Enable'
    - 'Tile01/Exposure'
    - 'Tile01/ExposureAuto'
    - 'Tile01/Gain'
    - 'Tile01/Zoom'
    - 'Tile02/Source'
    - 'Tile02/Enable'
    - 'Tile02/Exposure'
    - 'Tile02/ExposureAuto'
    - 'Tile02/Gain'
    - 'Tile02/Zoom'
    - 'Tile03/Source'
    - 'Tile03/Enable'
    - 'Tile03/Exposure'
    - 'Tile03/ExposureAuto'
    - 'Tile03/Gain'
    - 'Tile03/Zoom'
    - 'Tile04/Source'
    - 'Tile04/Enable'
    - 'Tile04/Exposure'
    - 'Tile04/ExposureAuto'
    - 'Tile04/Gain'
    - 'Tile04/Zoom'

pipeline:
  tiler_rows: 2
  tiler_columns: 2  
  width: 3840
  height: 2160
  sink_element: 'nv3dsink'
  streammux_config: '/home/seaonics/Dev/VideoWallOrin/VisionController/config/streammux_config.txt'
  max_num_sources: 4
  batched_push_timeout: 20000
  batch_size: 4
  sync_inputs: 0
  enable_pipeline: false
